# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BCKN!
email: ikbudget@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Hallo, ik ben Stefan. Ik werk als een IAM architect en sinds kort ben ik een enthousiaste budgeteer. 
  Hier leg ik uit waarom ik ons budget gestart ben en waarom ik denk dat jij dat ook moet doen. 
  Contacteer me voor meer info.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: stefanbckn
#github_username:  stefanbckn
permatype: micro
link: /:year/:month/:day/:title/
show_excerpts: true
excerpt_separator: <!--more-->


# Build settings
theme: plainwhite
author_name: Stefan Bocken

plugins:
  - jekyll-feed

# plainwhite theme settings
plainwhite:
  name: Stefan Bocken
  tagline: IAM & Sports Enthusiast, Budgeteer
  date_format: "%b %-d, %Y"
  portfolio_image: "assets/portfolio.jpg"
  search: true
  analytics_id: "254653227"
  navigation:
      - title: Home
        url: "/"
      - title: Blog
        url: "/blog"
      - title: Budget
        url: "/budget"
      - title: Foto's
        url: "https://photos.bckn.be"
      - title: About
        url: "/about"

  social_links:
    twitter: stefanbckn
    github: stefanbckn
    linkedIn: in/stefanbocken
    instagram: stefanbckn

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
